site_name: 许王伟的个人网站
site_url: https://xuwangwei.com
site_description: 我老婆说我是一个执着的人
site_author: 许王伟
theme:
  name: material
  language: zh
  font: false

  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: green
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: blue

  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow

nav:
  - 博客: 
      - blog/index.md
  - 漫游 MySQL 源码系列:
      - mysql/搭建MySQL源码阅读和调试环境.md
      - mysql/connect1.md

plugins:
  - tags
  - search
  - blog:
      # blog_dir: .
      # blog_toc: false
      # post_date_format: long
      # post_url_format: "{slug}"
      post_readtime: false
      # archive: true
      # archive_toc: true
  - redirects:
      redirect_maps:
        index.md: blog/index.md



markdown_extensions:
  - pymdownx.keys
  - pymdownx.tilde
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-58Y5WB8P5M